### ISSUE TITLE
Can the library handle many beacons?

### ISSUE THREAD

**Issue by MGasztold** [AltBeacon/spec#21]
Hello,

Do you have any experience with passing hundreds of beacons to BeaconService using startMonitoringBeaconInRegion or startRangingBeaconInRegion for each? Does it produce ANRs and is impossible to handle or should it work fine according to your tests?

Best Regards
MG

**Comment by davidgyoung** [comment]
@MGasztold I believe this question is about the Android Beacon Library.  Please open issues about that here:  https://github.com/AltBeacon/android-beacon-library/issues.  For the sake of expediency, I'll note here that we have tested that library with many dozens of beacons visible at the same time.  If the code cannot keep up with the number of bluetooth devices being tracked it will drop them, causing lost detections, rather than producing ANRs.
